/* Generated By:JavaCC: Do not edit this line. GrammerConstants.java */
package htmlParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUOTE = 5;
  /** RegularExpression Id. */
  int COMMAND = 6;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int SENTENCE = 9;
  /** RegularExpression Id. */
  int ELEMENT = 10;
  /** RegularExpression Id. */
  int IMAGE = 11;
  /** RegularExpression Id. */
  int DECORATED_TEXT = 12;
  /** RegularExpression Id. */
  int LINK = 13;
  /** RegularExpression Id. */
  int QSQ = 14;
  /** RegularExpression Id. */
  int COLOR = 15;
  /** RegularExpression Id. */
  int TEXT = 16;
  /** RegularExpression Id. */
  int FONT = 17;
  /** RegularExpression Id. */
  int AND = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\\"\"",
    "<COMMAND>",
    "<ALPHANUMERIC>",
    "\"null\"",
    "<SENTENCE>",
    "<ELEMENT>",
    "<IMAGE>",
    "<DECORATED_TEXT>",
    "<LINK>",
    "<QSQ>",
    "<COLOR>",
    "<TEXT>",
    "<FONT>",
    "\"AND\"",
  };

}
